### ISSUE TITLE
Recurrent Policy

### ISSUE THREAD

**Issue by MarcoMeter** [AntoineTheb/RNN-RL#1]
HI @AntoineTheb 
I just stumbled upon your repo. I can very well relate to the questions that you have stated, because I pretty much have the same ones. Are you still working on (interested in) this matter? I've been extensively working on a recurrent PPO implementation pretty much with the same goals.

**Comment by AntoineTheb** [comment]
Hey @MarcoMeter, thanks for your interest !
I got busy with my Masters but I was planning on working again on this repo in the next couple of months. In the meantime, if you feel like your findings may be relevant to this repo, I'm open to pull requests !
